name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v2
    # - name: Install modules
    # - run: npm install
    # - name: Run ESLint
    #   run: npm run eslint
    # - name: Run Unit Tests...
    #   run: npm run test
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Run ESLint
        run: npm run eslint
      - run: npm run test
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGILE_AFRICA_FA653 }}'
          channelId: live
          projectId: agile-africa-fa653